name: CI

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          # https://github.com/actions/setup-go/tree/v5#using-stableoldstable-aliases
          - stable
          - oldstable
          # https://github.com/actions/setup-go/tree/v5#getting-go-version-from-the-gomod-file
          - go.mod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go != 'go.mod' && matrix.go || null }}
          go-version-file: ${{ matrix.go == 'go.mod' && matrix.go || null }}
      - run: go test -v ./...
